sequenceDiagram
    participant browser
    participant server

    Note over browser,server: User clicks submit on the form

    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note

    Note left of server: Server saves new note
    server-->>browser: return HTTP status code 302 

    Note over browser, server: after success, new GET request to all notes

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/notes
    activate server
    server-->>browser: HTML document

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
    activate server
    server-->>browser: CSS file


    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.js
    activate server
    server-->>browser: Javascript (main.js)

    Note right of browser: De browser voert de JS-code uit die de JSON ophaalt

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
    activate server
    server-->>browser: Status 200, return data
