sequenceDiagram
    participant browser
    participant server

   browser ->> server: GET https://studies.cs.helsinki.fi/exampleapp/spa
   server -->> browser: HTML

   browser ->> server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
   server -->> browser: CSS


   browser ->> server: GET https://studies.cs.helsinki.fi/exampleapp/spa.js
   server -->> browser: JavaScript (spa.js)

   Note over browser, server:  JS will work to fetch the JSON

   browser ->> server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
   server -->> browser: Status: 200, data is returned

