sequenceDiagram
    participant browser
    participant server

    Note over browser,server: User clicks submit on the form

    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note
    activate server

    Note left of server: Server saves new note
    server-->>browser: return HTTP status code 302 
    deactivate server

    Note over browser, server: after success, new GET request to all notes

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/notes
    activate server
    server-->>browser: HTML document
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
    activate server
    server-->>browser: retrieve CSS file
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.js
    activate server
    server-->>browser: retrieve JS
    deactivate server

    Note right of browser: De browser voert de JS-code uit die de JSON ophaalt

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
    activate server
    server-->>browser: [{ "content": "HTML is easy", "date": "2023-1-1" }, ... ]
    deactivate server